// Illustrative data for practice. Prices are approximate, NOT live market values.
// 110 items so you get 11 pages at PAGE_SIZE = 10.
// Handy search tests: "bank" (many), "tata" (several), "power", "finance", "zzz" (empty state).

export const stocks = [
  {
    id: 1,
    name: "Reliance Industries",
    symbol: "RELIANCE",
    sector: "Energy",
    price: 2890.5,
  },
  {
    id: 2,
    name: "Tata Consultancy Services",
    symbol: "TCS",
    sector: "IT",
    price: 3950.2,
  },
  {
    id: 3,
    name: "HDFC Bank",
    symbol: "HDFCBANK",
    sector: "Banking",
    price: 1675.4,
  },
  { id: 4, name: "Infosys", symbol: "INFY", sector: "IT", price: 1520.8 },
  {
    id: 5,
    name: "ICICI Bank",
    symbol: "ICICIBANK",
    sector: "Banking",
    price: 1180.6,
  },
  {
    id: 6,
    name: "Hindustan Unilever",
    symbol: "HINDUNILVR",
    sector: "FMCG",
    price: 2380.1,
  },
  {
    id: 7,
    name: "State Bank of India",
    symbol: "SBIN",
    sector: "Banking",
    price: 820.3,
  },
  {
    id: 8,
    name: "Bharti Airtel",
    symbol: "BHARTIARTL",
    sector: "Telecom",
    price: 1560.9,
  },
  { id: 9, name: "ITC", symbol: "ITC", sector: "FMCG", price: 465.7 },
  {
    id: 10,
    name: "Larsen & Toubro",
    symbol: "LT",
    sector: "Infra",
    price: 3620.4,
  },
  {
    id: 11,
    name: "Kotak Mahindra Bank",
    symbol: "KOTAKBANK",
    sector: "Banking",
    price: 1790.2,
  },
  {
    id: 12,
    name: "Axis Bank",
    symbol: "AXISBANK",
    sector: "Banking",
    price: 1140.5,
  },
  {
    id: 13,
    name: "Bajaj Finance",
    symbol: "BAJFINANCE",
    sector: "Finance",
    price: 7150.0,
  },
  {
    id: 14,
    name: "Asian Paints",
    symbol: "ASIANPAINT",
    sector: "Consumer",
    price: 2860.3,
  },
  {
    id: 15,
    name: "Maruti Suzuki",
    symbol: "MARUTI",
    sector: "Auto",
    price: 12450.0,
  },
  {
    id: 16,
    name: "Sun Pharmaceutical",
    symbol: "SUNPHARMA",
    sector: "Pharma",
    price: 1680.4,
  },
  {
    id: 17,
    name: "Titan Company",
    symbol: "TITAN",
    sector: "Consumer",
    price: 3450.8,
  },
  {
    id: 18,
    name: "UltraTech Cement",
    symbol: "ULTRACEMCO",
    sector: "Cement",
    price: 11200.5,
  },
  {
    id: 19,
    name: "Nestle India",
    symbol: "NESTLEIND",
    sector: "FMCG",
    price: 2450.6,
  },
  { id: 20, name: "Wipro", symbol: "WIPRO", sector: "IT", price: 540.2 },
  {
    id: 21,
    name: "HCL Technologies",
    symbol: "HCLTECH",
    sector: "IT",
    price: 1620.7,
  },
  {
    id: 22,
    name: "Tech Mahindra",
    symbol: "TECHM",
    sector: "IT",
    price: 1590.3,
  },
  {
    id: 23,
    name: "Power Grid Corporation",
    symbol: "POWERGRID",
    sector: "Power",
    price: 325.9,
  },
  { id: 24, name: "NTPC", symbol: "NTPC", sector: "Power", price: 372.4 },
  {
    id: 25,
    name: "Tata Motors",
    symbol: "TATAMOTORS",
    sector: "Auto",
    price: 985.6,
  },
  {
    id: 26,
    name: "Tata Steel",
    symbol: "TATASTEEL",
    sector: "Metals",
    price: 158.3,
  },
  {
    id: 27,
    name: "JSW Steel",
    symbol: "JSWSTEEL",
    sector: "Metals",
    price: 985.1,
  },
  {
    id: 28,
    name: "Mahindra & Mahindra",
    symbol: "M&M",
    sector: "Auto",
    price: 2980.7,
  },
  {
    id: 29,
    name: "Bajaj Finserv",
    symbol: "BAJAJFINSV",
    sector: "Finance",
    price: 1740.2,
  },
  {
    id: 30,
    name: "Adani Enterprises",
    symbol: "ADANIENT",
    sector: "Conglomerate",
    price: 2450.9,
  },
  {
    id: 31,
    name: "Adani Ports",
    symbol: "ADANIPORTS",
    sector: "Infra",
    price: 1380.4,
  },
  {
    id: 32,
    name: "Oil and Natural Gas Corporation",
    symbol: "ONGC",
    sector: "Energy",
    price: 268.5,
  },
  {
    id: 33,
    name: "Coal India",
    symbol: "COALINDIA",
    sector: "Mining",
    price: 415.2,
  },
  {
    id: 34,
    name: "IndusInd Bank",
    symbol: "INDUSINDBK",
    sector: "Banking",
    price: 1120.8,
  },
  {
    id: 35,
    name: "Dr. Reddy's Laboratories",
    symbol: "DRREDDY",
    sector: "Pharma",
    price: 6280.4,
  },
  { id: 36, name: "Cipla", symbol: "CIPLA", sector: "Pharma", price: 1520.6 },
  {
    id: 37,
    name: "Divi's Laboratories",
    symbol: "DIVISLAB",
    sector: "Pharma",
    price: 5890.3,
  },
  {
    id: 38,
    name: "Apollo Hospitals",
    symbol: "APOLLOHOSP",
    sector: "Healthcare",
    price: 6950.7,
  },
  {
    id: 39,
    name: "Eicher Motors",
    symbol: "EICHERMOT",
    sector: "Auto",
    price: 4890.2,
  },
  {
    id: 40,
    name: "Hero MotoCorp",
    symbol: "HEROMOTOCO",
    sector: "Auto",
    price: 4620.5,
  },
  {
    id: 41,
    name: "Bajaj Auto",
    symbol: "BAJAJ-AUTO",
    sector: "Auto",
    price: 9450.8,
  },
  {
    id: 42,
    name: "Grasim Industries",
    symbol: "GRASIM",
    sector: "Cement",
    price: 2680.4,
  },
  {
    id: 43,
    name: "Hindalco Industries",
    symbol: "HINDALCO",
    sector: "Metals",
    price: 645.9,
  },
  {
    id: 44,
    name: "Britannia Industries",
    symbol: "BRITANNIA",
    sector: "FMCG",
    price: 5120.3,
  },
  {
    id: 45,
    name: "Tata Consumer Products",
    symbol: "TATACONSUM",
    sector: "FMCG",
    price: 1085.6,
  },
  {
    id: 46,
    name: "SBI Life Insurance",
    symbol: "SBILIFE",
    sector: "Insurance",
    price: 1480.2,
  },
  {
    id: 47,
    name: "HDFC Life Insurance",
    symbol: "HDFCLIFE",
    sector: "Insurance",
    price: 690.4,
  },
  {
    id: 48,
    name: "Shriram Finance",
    symbol: "SHRIRAMFIN",
    sector: "Finance",
    price: 3050.7,
  },
  { id: 49, name: "LTIMindtree", symbol: "LTIM", sector: "IT", price: 5420.1 },
  {
    id: 50,
    name: "Bharat Petroleum",
    symbol: "BPCL",
    sector: "Energy",
    price: 328.6,
  },
  {
    id: 51,
    name: "Indian Oil Corporation",
    symbol: "IOC",
    sector: "Energy",
    price: 162.4,
  },
  {
    id: 52,
    name: "GAIL (India)",
    symbol: "GAIL",
    sector: "Energy",
    price: 205.7,
  },
  {
    id: 53,
    name: "Jio Financial Services",
    symbol: "JIOFIN",
    sector: "Finance",
    price: 320.5,
  },
  {
    id: 54,
    name: "Bank of Baroda",
    symbol: "BANKBARODA",
    sector: "Banking",
    price: 245.8,
  },
  {
    id: 55,
    name: "Punjab National Bank",
    symbol: "PNB",
    sector: "Banking",
    price: 108.4,
  },
  {
    id: 56,
    name: "Canara Bank",
    symbol: "CANBK",
    sector: "Banking",
    price: 112.6,
  },
  {
    id: 57,
    name: "Federal Bank",
    symbol: "FEDERALBNK",
    sector: "Banking",
    price: 192.3,
  },
  {
    id: 58,
    name: "IDFC First Bank",
    symbol: "IDFCFIRSTB",
    sector: "Banking",
    price: 72.5,
  },
  {
    id: 59,
    name: "Yes Bank",
    symbol: "YESBANK",
    sector: "Banking",
    price: 20.4,
  },
  { id: 60, name: "Vedanta", symbol: "VEDL", sector: "Metals", price: 445.7 },
  {
    id: 61,
    name: "Havells India",
    symbol: "HAVELLS",
    sector: "Consumer",
    price: 1580.2,
  },
  {
    id: 62,
    name: "Pidilite Industries",
    symbol: "PIDILITIND",
    sector: "Chemicals",
    price: 3050.9,
  },
  {
    id: 63,
    name: "Godrej Consumer Products",
    symbol: "GODREJCP",
    sector: "FMCG",
    price: 1240.6,
  },
  {
    id: 64,
    name: "Dabur India",
    symbol: "DABUR",
    sector: "FMCG",
    price: 520.3,
  },
  { id: 65, name: "Marico", symbol: "MARICO", sector: "FMCG", price: 685.4 },
  {
    id: 66,
    name: "Colgate-Palmolive India",
    symbol: "COLPAL",
    sector: "FMCG",
    price: 2920.8,
  },
  {
    id: 67,
    name: "Berger Paints",
    symbol: "BERGEPAINT",
    sector: "Consumer",
    price: 515.7,
  },
  {
    id: 68,
    name: "Siemens",
    symbol: "SIEMENS",
    sector: "Capital Goods",
    price: 6850.2,
  },
  {
    id: 69,
    name: "ABB India",
    symbol: "ABB",
    sector: "Capital Goods",
    price: 7120.4,
  },
  {
    id: 70,
    name: "Bharat Electronics",
    symbol: "BEL",
    sector: "Defence",
    price: 295.6,
  },
  {
    id: 71,
    name: "Hindustan Aeronautics",
    symbol: "HAL",
    sector: "Defence",
    price: 4350.8,
  },
  {
    id: 72,
    name: "Tata Power",
    symbol: "TATAPOWER",
    sector: "Power",
    price: 395.2,
  },
  {
    id: 73,
    name: "Adani Green Energy",
    symbol: "ADANIGREEN",
    sector: "Power",
    price: 1120.5,
  },
  {
    id: 74,
    name: "Adani Power",
    symbol: "ADANIPOWER",
    sector: "Power",
    price: 620.3,
  },
  { id: 75, name: "DLF", symbol: "DLF", sector: "Real Estate", price: 810.7 },
  {
    id: 76,
    name: "Godrej Properties",
    symbol: "GODREJPROP",
    sector: "Real Estate",
    price: 2780.4,
  },
  {
    id: 77,
    name: "Macrotech Developers",
    symbol: "LODHA",
    sector: "Real Estate",
    price: 1280.6,
  },
  {
    id: 78,
    name: "InterGlobe Aviation",
    symbol: "INDIGO",
    sector: "Aviation",
    price: 4620.9,
  },
  { id: 79, name: "Trent", symbol: "TRENT", sector: "Retail", price: 6450.3 },
  {
    id: 80,
    name: "Avenue Supermarts",
    symbol: "DMART",
    sector: "Retail",
    price: 4120.7,
  },
  {
    id: 81,
    name: "Page Industries",
    symbol: "PAGEIND",
    sector: "Textiles",
    price: 42500.0,
  },
  {
    id: 82,
    name: "Info Edge (India)",
    symbol: "NAUKRI",
    sector: "Consumer Tech",
    price: 7450.2,
  },
  {
    id: 83,
    name: "One 97 Communications",
    symbol: "PAYTM",
    sector: "Fintech",
    price: 780.4,
  },
  {
    id: 84,
    name: "PB Fintech",
    symbol: "POLICYBZR",
    sector: "Fintech",
    price: 1750.6,
  },
  {
    id: 85,
    name: "Angel One",
    symbol: "ANGELONE",
    sector: "Finance",
    price: 2850.3,
  },
  {
    id: 86,
    name: "Bajaj Housing Finance",
    symbol: "BAJAJHFL",
    sector: "Finance",
    price: 118.4,
  },
  {
    id: 87,
    name: "Muthoot Finance",
    symbol: "MUTHOOTFIN",
    sector: "Finance",
    price: 2150.8,
  },
  {
    id: 88,
    name: "Cholamandalam Investment",
    symbol: "CHOLAFIN",
    sector: "Finance",
    price: 1480.5,
  },
  {
    id: 89,
    name: "Power Finance Corporation",
    symbol: "PFC",
    sector: "Finance",
    price: 465.2,
  },
  {
    id: 90,
    name: "REC Limited",
    symbol: "RECLTD",
    sector: "Finance",
    price: 520.7,
  },
  {
    id: 91,
    name: "Torrent Pharmaceuticals",
    symbol: "TORNTPHARM",
    sector: "Pharma",
    price: 3250.4,
  },
  { id: 92, name: "Lupin", symbol: "LUPIN", sector: "Pharma", price: 2050.6 },
  {
    id: 93,
    name: "Zydus Lifesciences",
    symbol: "ZYDUSLIFE",
    sector: "Pharma",
    price: 980.3,
  },
  {
    id: 94,
    name: "Max Healthcare",
    symbol: "MAXHEALTH",
    sector: "Healthcare",
    price: 1120.8,
  },
  {
    id: 95,
    name: "Ashok Leyland",
    symbol: "ASHOKLEY",
    sector: "Auto",
    price: 225.4,
  },
  {
    id: 96,
    name: "TVS Motor Company",
    symbol: "TVSMOTOR",
    sector: "Auto",
    price: 2480.7,
  },
  { id: 97, name: "Bosch", symbol: "BOSCHLTD", sector: "Auto", price: 32500.0 },
  {
    id: 98,
    name: "Ambuja Cements",
    symbol: "AMBUJACEM",
    sector: "Cement",
    price: 560.2,
  },
  {
    id: 99,
    name: "Shree Cement",
    symbol: "SHREECEM",
    sector: "Cement",
    price: 26800.5,
  },
  { id: 100, name: "ACC", symbol: "ACC", sector: "Cement", price: 2150.4 },
  {
    id: 101,
    name: "Tata Communications",
    symbol: "TATACOMM",
    sector: "Telecom",
    price: 1750.3,
  },
  {
    id: 102,
    name: "Vodafone Idea",
    symbol: "IDEA",
    sector: "Telecom",
    price: 8.6,
  },
  {
    id: 103,
    name: "Petronet LNG",
    symbol: "PETRONET",
    sector: "Energy",
    price: 320.9,
  },
  {
    id: 104,
    name: "Container Corporation of India",
    symbol: "CONCOR",
    sector: "Logistics",
    price: 780.5,
  },
  {
    id: 105,
    name: "Persistent Systems",
    symbol: "PERSISTENT",
    sector: "IT",
    price: 5250.6,
  },
  { id: 106, name: "Coforge", symbol: "COFORGE", sector: "IT", price: 6120.4 },
  { id: 107, name: "Mphasis", symbol: "MPHASIS", sector: "IT", price: 2780.2 },
  {
    id: 108,
    name: "Tata Elxsi",
    symbol: "TATAELXSI",
    sector: "IT",
    price: 6450.7,
  },
  {
    id: 109,
    name: "Polycab India",
    symbol: "POLYCAB",
    sector: "Capital Goods",
    price: 6380.9,
  },
  {
    id: 110,
    name: "Voltas",
    symbol: "VOLTAS",
    sector: "Consumer",
    price: 1520.3,
  },
];

// Usage in your component:
//   import { stocks } from "./stocks";
//   <SearchPage data={stocks} />
//
// For the API follow-up, mock it locally:
//   export const fetchStocks = ({ q = "", page = 1, limit = 10 }) =>
//     new Promise((resolve) => {
//       setTimeout(() => {
//         const query = q.trim().toLowerCase();
//         const matched = query
//           ? stocks.filter((s) => s.name.toLowerCase().includes(query))
//           : stocks;
//         const start = (page - 1) * limit;
//         resolve({ items: matched.slice(start, start + limit), total: matched.length });
//       }, 400); // fake network delay
//     });
